apiVersion: v1
kind: Service
metadata:
  namespace: web-app
  name: service-web-app
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: app-web-app