apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: eks-auto-alb
spec:
  scheme: internet-facing
  ipAddressType: ipv4
  {{- if not (quote .Values.acmTlsArn | empty) }}
  certificateARNs:
    - {{ .Values.acmTlsArn }}
  {{- end -}}
