apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Chart.name }}
  name: deployment-{{ .Chart.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-{{ .Chart.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-{{ .Chart.name }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          minDomains: 2
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: app-{{ .Chart.name }}
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: Always
          name: {{ .Chart.name }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          livenessProbe:
            httpGet:
              path: /hello
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
