apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Chart.Name }}
  name: deployment-{{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-{{ .Chart.Name }}
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-{{ .Chart.Name }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          minDomains: 2
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: app-{{ .Chart.Name }}
      containers:
        - image: gradyent/tech-interview:latest
          imagePullPolicy: Always
          name: app-{{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.targetPort }}
          livenessProbe:
            httpGet:
              path: /hello
              port: {{ .Values.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
