# Helm values can be highly configurable and in-depth; this is just a simple example.
# Required
image: "gradyent/tech-interview:latest"
replicaCount: 3
sourcePort: 80
targetPort: 8080

# Optional - uncomment and provide value from IAC ACM output to enable TLS encryption
acmTlsArn: "arn:aws:acm:eu-west-1:530589290119:certificate/7604e7b4-f1c2-4511-b880-34b1a7138bf1"
